### ISSUE TITLE
生成jj排行榜和淫啪介绍失败了

### ISSUE THREAD

**Issue by KnightK22** [BeiYazi0/yinpa#1]
![image](https://github.com/BeiYazi0/yinpa/assets/57353187/9d8d3480-bec6-49f9-ad71-ba1d71cc2088)
如图，这个该如何解决

**Comment by BeiYazi0** [comment]
看上去像是缺少字体文件造成的。
在C:\Windows\Fonts文件夹搜索simsun.ttc确保存在该字体文件。

**Comment by KnightK22** [comment]
> 看上去像是缺少字体文件造成的。 在C:\Windows\Fonts文件夹搜索simsun.ttc确保存在该字体文件。

解决了，谢谢大佬
